# Generated by Django 4.2.5 on 2023-12-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categories', models.CharField(choices=[('music', 'Music'), ('hamburger', 'Food'), ('martini-glass-citrus', 'Drink'), ('computer', 'Coding'), ('heart-pulse', 'Health and Fitness'), ('otter', 'Other'), ('language', 'Languages'), ('location-dot', 'Travel'), ('list-ol', 'Forty Day Challenges'), ('briefcase', 'Admin'), ('palette', 'Creativity')], default='Other', max_length=50)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
